name: TokenShop
version: 1.0
author: StovenC
main: me.stovenc.rubyshop.Core
description: Token Shop Core

commands:
  tokens:
    aliases: [token]
    description: Token Core
permissions:
  tokens.shop:
    description: Player shop command!
    default: op
  tokens.bal:
    description: Player balance command!
    default: op
  tokens.pay:
    description: Player pay command!
    default: op
  tokens.set:
    description: Admin set command!
    default: op
  tokens.add:
    description: Admin add command!
    default: op
  tokens.remove:
    description: Admin remove command!
    default: op
  tokens.baltop:
    description: Player balance top command!
    default: op